---
# tools wget and etc.

- name: Upgraded all packages
  yum:
    name: '*'
    state: latest

- name: Delete packages
  yum: pkg={{ item }} state=removed
  with_items:
    - cronie-anacron

- name: Installed repo=epel
  yum:
    pkg: epel-release
    state: latest
  
- name: Install packages to compile kernel and trouble shooting tools
  yum: pkg={{ item }} state=latest
  with_items:
    - gcc
    - ncurses-devel
    - bc
    - perl
    - cronie-noanacron
    - wget
    - net-tools
    - strace
    - psmisc
    - lsof
    - bind-utils
    - nc
    - atop
    - iftop
    - unzip

- name: Changed values of sysctl
  sysctl: name="{{ item.name }}" value="{{ item.value }}" sysctl_set=yes state=present
  with_items:
    - { name: 'net.core.somaxconn', value: 1024 }
    - { name: 'net.core.rmem_max', value: 8388608 }
    - { name: 'net.core.wmem_max', value: 8388608 }
    - { name: 'net.core.rmem_default', value: 65536 }
    - { name: 'net.core.wmem_default', value: 65536 }
    - { name: 'net.ipv4.tcp_rmem', value: 4096 87380 8388608 }
    - { name: 'net.ipv4.tcp_wmem', value: 4096 65536 8388608 }
    - { name: 'net.ipv4.tcp_mem', value: 8388608 8388608 8388608 }
    - { name: 'vm.swappiness', value: 1 }

- name: Disabled units of SystemD
  service: name="{{ item }}" state=stopped enabled=no masked=yes
  with_items:
    - NetworkManager.service
    - NetworkManager-wait-online.service

- name: Restarted network.service
  service: name=network.service

- name: Loaded module zram.ko
  modprobe:
    name: zram
    state: present
    params: 'num_devices=2'

- name: Enabled zram
  shell: for i in 0 1; do /bin/echo 268435456 > /sys/block/zram$i/disksize && mkswap /dev/zram$i && swapon /dev/zram$i -p 10 && /bin/grep zram$i /etc/fstab || /bin/echo -e "/dev/zram$i\t\t\tswap\t\t\tswap\tpri=10 0 0" >> /etc/fstab; done

- name: Inserted modules-load.d/zram.conf
  copy: src=modules-load.d_zram.conf dest=/etc/modules-load.d/zram.conf
- name: Inserted modprobe.d/zram.conf
  copy: src=modprobe.d_zram.conf dest=/etc/modprobe.d/zram.conf
- name: Inserted udev/rules.d/10-zram.rules
  copy: src=udev_rules.d_10-zram.rules dest=/etc/udev/rules.d/10-zram.rules

