---
haproxy_socket: /var/lib/haproxy/stats
haproxy_chroot: /var/lib/haproxy
haproxy_user: haproxy
haproxy_group: haproxy
haproxy_pass: haproxy

# Frontend settings.
haproxy_frontend_name: 'hafrontend'
haproxy_frontend_bind_address: '*'
haproxy_frontend_port: 80
haproxy_frontend_mode: 'http'

# Backend settings.
haproxy_backend_name: 'habackend'
haproxy_backend_mode: 'http'
haproxy_backend_balance_method: 'roundrobin'

# List of backend servers.
haproxy_backend_servers:
  - name: web01
    address: 192.168.10.101
  - name: web02
    address: 192.168.10.102

# Extra global vars (see README for example usage).
haproxy_global_vars: []
